-- Avatar multi-agents & preview image support

-- 1) Ensure avatar_profiles has primary + preview columns
alter table if exists public.avatar_profiles
  add column if not exists is_primary boolean default false,
  add column if not exists preview_image_url text,
  add column if not exists preferred_agent_id uuid;

-- 2) Image agents registry (multi-model support for avatars & images)
create table if not exists public.image_agents (
  id uuid primary key default gen_random_uuid(),
  display_name text not null,
  provider_model_id text not null,
  kind text,
  is_recommended boolean default false,
  quality_score numeric,
  default_cfg jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists image_agents_kind_idx
  on public.image_agents (kind, is_recommended desc, created_at desc);

grant select, insert, update, delete on table public.image_agents to anon, authenticated;

-- 3) Avatar previews generated by multiple agents
create table if not exists public.avatar_previews (
  id uuid primary key default gen_random_uuid(),
  avatar_profile_id uuid not null references public.avatar_profiles(id) on delete cascade,
  agent_id uuid not null references public.image_agents(id) on delete restrict,
  image_url text not null,
  is_selected boolean default false,
  created_at timestamptz not null default now()
);

create index if not exists avatar_previews_avatar_idx
  on public.avatar_previews (avatar_profile_id, created_at desc);

create index if not exists avatar_previews_selected_idx
  on public.avatar_previews (avatar_profile_id, is_selected);

grant select, insert, update, delete on table public.avatar_previews to anon, authenticated;
